# Generated by Django 5.1.3 on 2024-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_profile',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/'),
        ),
    ]
