# Generated by Django 5.1.3 on 2024-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mentor_mentor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
