# Generated by Django 5.1.3 on 2024-12-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_payment_method_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting Verification', 'Waiting Verification'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
